version: '3.3'

volumes:
  geth-mainnet: {}

services:
  geth-mainnet:
    image: golang-geth-arm:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8546"
      - "30303"
    volumes:
      - /Volumes/data/geth:/geth
    command: '--syncmode fast --ipcdisable --ws --ws.addr 0.0.0.0 --ws.origins="*" --datadir /geth --cache 2500 --verbosity 3'
