version: '3.3'

volumes:
  geth-mainnet: {}

services:
  geth-mainnet:
    image: golang-geth-arm
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - /home/pi/.geth:/geth
    command: '--syncmode fast --ws --ipcdisable --ws.addr 0.0.0.0 --ws.origins="*" --datadir /geth --verbosity 3'
